#!/bin/bash
# Quick Railway.app MongoDB Setup Script

echo "🚀 Railway.app MongoDB Deployment Guide"
echo "====================================="
echo ""
echo "1. Go to https://railway.app"
echo "2. Sign in with GitHub"
echo "3. Click 'New Project' → 'Deploy from GitHub repo'"
echo "4. Connect your GitHub account"
echo "5. Select your solutil repository"
echo "6. Add MongoDB service:"
echo "   - Click 'Add Service' → 'Database' → 'MongoDB'"
echo "7. Copy the connection string from Railway dashboard"
echo "8. Update your .env file with the new MONGODB_URI"
echo ""
echo "Example Railway MongoDB connection string:"
echo "MONGODB_URI=mongodb://root:password@mongodb.railway.app:27017/railway"
echo ""
echo "✅ Free tier includes:"
echo "   - 512MB RAM"
echo "   - 1GB storage"
echo "   - Perfect for development/testing"
